//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Inspekcijska_kontrola_proizvoda.Models
{
   
    public partial class InspekcijskaKontrola
    {
        public int InspekcijskaKontrolaID { get; set; }

        [Required(ErrorMessage = "Molimo odaberite proizvod")]
        [Display(Name = "Kontrolisani proizvod")]
        public int ProizvodID { get; set; }


        [Required(ErrorMessage = "Molimo odaberite naziv inspekcijskog tijela")]
        [Display(Name = "Nadležno inspekcijsko tijelo")]
        public int InspekcijskoTijeloID { get; set; }


        [DataType(DataType.Date)]
        [Required(ErrorMessage = "Molimo odaberite datum kontrole")]
        [Display(Name = "Datum kontrole")]
        public System.DateTime DatumKontrole { get; set; }


        [Required(ErrorMessage = "Molimo opišite rezultate kontrole")]
        [Display(Name = "Rezultat kontrole")]
        public string RezultatiKontrole { get; set; }


        [Display(Name = "Proizvod siguran")]
        public bool ProizvodSiguran { get; set; }

        public bool Izbrisan { get; set; }
    
        public virtual InspekcijskoTijelo InspekcijskoTijelo { get; set; }
        public virtual Proizvod Proizvod { get; set; }
    }
}
