//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspekcijska_kontrola_proizvoda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspektorat
    {
      
    
        public int InspektoratID { get; set; }
        public string NazivInspektorata { get; set; }
    
        public virtual ICollection<InspekcijskoTijelo> InspekcijskoTijelo { get; set; }
    }
}
