//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspekcijska_kontrola_proizvoda.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ping_inspekcijska_kontrola_proizvodaEntities : DbContext
    {
        public ping_inspekcijska_kontrola_proizvodaEntities()
            : base("name=ping_inspekcijska_kontrola_proizvodaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<InspekcijskaKontrola> InspekcijskaKontrola { get; set; }
        public virtual DbSet<InspekcijskoTijelo> InspekcijskoTijelo { get; set; }
        public virtual DbSet<Inspektorat> Inspektorat { get; set; }
        public virtual DbSet<Proizvod> Proizvod { get; set; }
    }
}
