//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspekcijska_kontrola_proizvoda.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Proizvod
    {
        
    
        public int ProizvodID { get; set; }

        [Required(ErrorMessage = "Molimo unesite naziv proizvoda")]
        [Display(Name = "Naziv proizvoda")]
        public string NazivProizvoda { get; set; }


        [Display(Name = "Proizvoðaè")]
        [Required(ErrorMessage = "Molimo unesite naziv proizvoðaèa")]
        public string Proizvodjac { get; set; }


        [Display(Name = "Serijski broj")]
        public string SerijskiBroj { get; set; }

        [Display(Name = "Zemlja porijekla")]
        [Required(ErrorMessage = "Molimo unesite zemlju porijekla proizvoda")]
        public string ZemljaPorijekla { get; set; }

        [Display(Name = "Opis proizvoda")]
        public string Opis { get; set; }

        public bool Izbrisan { get; set; }
    
        public virtual ICollection<InspekcijskaKontrola> InspekcijskaKontrola { get; set; }
    }
}
